---
- name: Installing NOPcommerce
  hosts: all
  become: yes
  tasks:
  - name: Download Microsoft key 
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      dest: /tmp/packages-microsoft-prod.deb
      mode: '755'
  - name: Prevent python from being upgraded
    dpkg_selections:
      name: /tmp/packages-microsoft-prod.deb
      selection: install