---
- name: Installing NOPcommerce
  hosts: all
  become: yes
  tasks:
    - name: Download Microsoft key 
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 
        dest: /tmp/packages-microsoft-prod.deb
        mode: '755'
    - name: deb need to install
      ansible.builtin.apt:
        deb: /tmp/packages-microsoft-prod.deb 
    - name: .net core runtime
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - unzip
        - apt-transport-https
        - aspnetcore-runtime-6.0  
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Start service nginx
      ansible.builtin.service:
        name: nginx
        state: started 
    - name: Configure reverse proxy
      ansible.builtin.copy:
        src: ./forward.conf
        dest: /etc/nginx/sites-available/default
      notify:
      - Restart nginx
    - name: creating the drirectory for nopcommerce bundle
      ansible.builtin.file:
        path: /var/www/nopCommerce450/
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
    - name: Download nopcommerce bundle
      get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.50.2/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce450/nopCommerce_4.50.2_NoSource_linux_x64.zip
    - name: Extract .zip
      ansible.builtin.unarchive:
        src: /var/www/nopCommerce450/nopCommerce_4.50.2_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce450/
        remote_src: yes
    - name: creating couple directories
      ansible.builtin.file:
        path: 
        - /var/www/nopCommerce450/bin
        - /var/www/nopCommerce450/logs
        state: directory   
    - name: creating nopCommerce service
      ansible.builtin.copy:
        src: ./nopCommerce450.service
        dest: /etc/systemd/system/
    - name: nopcommerce restart
      ansible.builtin.systemd:
        state: started
        name: nopCommerce450.service
        daemon_reload: yes
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
             
                  
